#ifndef __PARAM_TYPES_H
#define __PARAM_TYPES_H

#define	PARAM_SERVER_CODE			0x01
#define	PARAM_USER_NAME				0x02
#define	PARAM_PASSWORDS				0x03	
#define	PARAM_APN					0x04
#define	PARAM_SIMPIN				0x05

#define	PARAM_LOCAL_MT				0x06
#define	PARAM_LOCAL_PORT			0x07	
#define	PARAM_TIMEVAL				0x08
#define	PARAM_PACK_LEN				0x09
#define	PARAM_RECONNECT_INTERVAL	0x0a
#define	PARAM_DEBUG_TYPE			0x0b
#define	PARAM_LAST_PACKET_IDLE		0x0c	

#define	PARAM_CENTER_ADDR			0x0d
#define	PARAM_CENTER_NAME			0x0e	
#define	PARAM_DOMAIN_TTL			0x0f	
#define	PARAM_CENTER_PORT			0x10	
#define	PARAM_DNS_ADDR				0x11
#define	PARAM_SEC_CENTER_ADDR		0x20
#define	PARAM_SEC_CENTER_PORT		0x21	

#define	PARAM_SERIAL_PORT			0x12

#define	PARAM_MT_TYPE				0x13
#define	PARAM_CALL_TYPE				0x14
#define	PARAM_CALL_TIMEVAL			0x15
#define	PARAM_OFF_LINETIME			0x16
#define	PARAM_PEER_MT				0x17

#define	PARAM_TRANSPORT_TYPE		0x18
#define	PARAM_DSC_CONNECTION_TYPE	0x19

#define	PARAM_VERSION				0x30
#define	PARAM_HARDWARE_VERSION		0x31
#define	PARAM_PROGRAM_BUILT_DATE	0x32

#define	PARAM_PRODUCER_TYPE			0x1a

#define	PARAM_TCP_KEEPIDLE			0x22
#define	PARAM_IDENTIFIER_SEPARATOR	0x23
#define	PARAM_PPPKEEPALIVE			0x24
#define	PARAM_CUSTOM_HEART_LEN		0x25
#define	PARAM_CUSTOM_HEART			0x26

#endif